tasks:
- install:
- ceph:
- rgw: [client.0]
- s3tests:
    client.0:
      force-branch: wip-pacific-461
      git_remote: https://github.com/cbodley/
      rgw_server: client.0
overrides:
  ceph:
    conf:
      client:
        rgw lc debug interval: 10
