tasks:
- install:
- ceph:
- rgw: [client.0]
- tox: [client.0]
- ragweed:
    client.0:
      force-branch: wip-67986
      rgw_server: client.0
      stages: prepare
- ragweed:
    client.0:
      force-branch: wip-67986
      rgw_server: client.0
      stages: check
