tasks:
- install:
- ceph: {cluster: c1}
- ceph: {cluster: c2}
- rgw:
    c1.client.0:
      valgrind: [--tool=memcheck]
    c1.client.1:
      valgrind: [--tool=memcheck]
    c2.client.0:
      valgrind: [--tool=memcheck]
    c2.client.1:
      valgrind: [--tool=memcheck]
- rgw-multisite:
- rgw-multisite-tests:
